<?php require("template/header.phtml") ?>
<form method = "post" action = "" class="form text-primary" >
    <!-- SEARCH BAR -->
    <!-- Search by user id. Whilst the user is typing inside the search bar, provide the user with smart user suggestions -->
    <div class="form-group" >
        <label for="search" > Search by User ID </label >
        <input type = "text" class="form-control" placeholder = "<?php
        if (isset($_SESSION["search"]))
        {
            echo $_SESSION["search"];
        } else {
            echo "Search by User ID";
        }
        ?>" name = "search" onkeyup="showHint(this.value)">
        <p>Suggestions: <span id="txtHint"></span></p>
    </div >
    <script>
        function showHint(userInput) {
            if (userInput.length == 0) {
                document.getElementById("txtHint").innerHTML = "";
                return;
            } else {
                var xmlhttp = new XMLHttpRequest();

                xmlhttp.onreadystatechange = function() {
                    if (this.readyState == 4 && this.status == 200) {
                        var uic = document.getElementById("txtHint");
                        uic.innerHTML = this.responseText;
                    }
                };
                xmlhttp.open("GET", "getHint.php?q=" + userInput, true);
                xmlhttp.send();
            }
        }
    </script>
    <!-- enter the search, if there has been a search already, provide the user to reset the filter -->
    <input type = "submit" class="btn btn-primary" name = "searchbutton" value = "Search" >
    <?php
    if (isset($_SESSION["search"])) {
        echo "<input type='submit' class='btn btn-primary' name='clearsearchbutton' value='Clear Search'>";
    } ?>
</form >
<!-- USERS LIST -->
<form method="post" action="" class="form text-primary">
    <br>
    <table class="table table-hover">
        <thead>
        <?php
        if (isset(($_SESSION["login"]))) {
            echo '<tr><th>User ID</th><th>First name</th><th>Surname</th><th>Email</th><th>Send/Remove Friend Request</th></tr>';
        } else {
            echo '<tr><th>User ID</th><th>Log in to see more!</th>';
        }
        ?>
        </thead>
        <tbody>
        <?php
        // check if the user is logged in
        if (isset(($_SESSION["login"]))) {
            // check all users for friendship. If true, display already added button else display add friend functionality.
            foreach ($view->usersTableDataSet as $userTableData) {
                if (strtolower($userTableData->getUserID()) != strtolower($_SESSION["login"])) {
                    $isFriend = false;
                    echo '<tr> <td>' . $userTableData->getUserID() . '</td> <td>' . $userTableData->getFirstName() . '</td> <td>' . $userTableData->getSurname() . '</td> <td>' . $userTableData->getEmail() . '</td>';
                        foreach ($view->friendsTableDataSet as $friendsTableData) {
                            if ((strcmp($friendsTableData->getSender(),  $userTableData->getUserID()) == 0 && strcmp($friendsTableData->getRecipient(), $_SESSION['login']) == 0) || (strcmp($friendsTableData->getRecipient(),  $userTableData->getUserID()) == 0 && strcmp($friendsTableData->getSender(), $_SESSION['login']) == 0)) {
                                $isFriend = true;
                            }
                        }
                        if ($isFriend) {
                                echo '<td><input type="submit" class="btn btn-secondary" name="addedFriend" value="Add ' . $userTableData->getUserID() . '">';
                            } else {
                                echo '<td><input type="submit" class="btn btn-primary" name="addFriend" value="Add ' . $userTableData->getUserID() . '">';
                        }
                        echo '</td>' . '</td>' . '</tr>';
                }
            }
        } else {
            // if the user is not logged in, then they will only be able to see the userID of the users.
            foreach ($view->usersTableDataSet as $userTableData) {
                echo '<tr> <td>' . $userTableData->getUserID() . '</td> <td>Log in to view more information</td>' . '</td></tr>';
            }
        }
        ?>
        </tbody>
    </table>
</form>